#!/usr/bin/env bash
# ==============================================================================
# twin-polari-build.sh — launch instance B beside the running staging stack
# and wire the peer handshake (Track 2 of DISTRIBUTED_COMPUTE_PLAN.md).
#
# USAGE
#   ./twin-polari-build.sh            # up: network, wiring, B, handshake
#   ./twin-polari-build.sh down       # stop instance B (A untouched)
#   ./twin-polari-build.sh status     # peers as A and B each see them
#
# WHAT IT DOES (idempotent; safe to re-run — and SHOULD be re-run after any
# rebuild of instance A, since docker update/network connect/token-file do
# not survive container re-creation):
#   1. Ensures the `polari-link` peer network exists.
#   2. Wires instance A (the running prf-backend) into the twin:
#        - joins it to polari-link,
#        - raises its memory to 1 GB (dask sizing; live, no recreation),
#        - drops the shared peer token into its data volume
#          (/app/data/peer_token — read as the env-var fallback).
#   3. Generates B's frontend runtime config (plain-HTTP ports).
#   4. Brings up instance B (project `polari-twin-b`) — same images, own
#      data volume, shared Keycloak/MariaDB/MinIO over A's network.
#   5. Registers each instance as the other's peer (shared token).
#
# Instance A stays fully intact: same URLs, same flow, same rebuild script.
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_B="$SCRIPT_DIR/docker-compose.twin-b.yml"
ENV_FILE="$SCRIPT_DIR/.generated/.env.staging"
TOKEN_FILE="$SCRIPT_DIR/.generated/.polari-peer-token"
PROJECT_B="polari-twin-b"

G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; R='\033[0;31m'; NC='\033[0m'

if docker info >/dev/null 2>&1; then DOCKER="docker"; else DOCKER="sudo docker"; fi

LOCAL_IP=$(grep -oP '^LOCAL_IP=\K.*' "$ENV_FILE" 2>/dev/null | tr -d '"' || true)
[[ -n "$LOCAL_IP" ]] || { echo -e "${R}[error]${NC} LOCAL_IP not found — run ./staging-setup.sh first"; exit 1; }

A_API="https://api.prf.${LOCAL_IP}.nip.io"
B_API="http://${LOCAL_IP}:8081"

cmd="${1:-up}"

if [[ "$cmd" == "down" ]]; then
    echo -e "${B}[twin]${NC} stopping instance B (instance A untouched)…"
    POLARI_PEER_TOKEN=unused $DOCKER compose -p "$PROJECT_B" -f "$COMPOSE_B" down
    echo -e "${G}[twin]${NC} instance B down."
    exit 0
fi

if [[ "$cmd" == "status" ]]; then
    echo -e "${B}[twin]${NC} peers as instance A sees them:"
    curl -k -s "$A_API/api/peers" | python3 -m json.tool || true
    echo -e "${B}[twin]${NC} peers as instance B sees them:"
    curl -s "$B_API/api/peers" | python3 -m json.tool || true
    exit 0
fi

# ---- 1. peer network -----------------------------------------------------
$DOCKER network inspect polari-link >/dev/null 2>&1 \
    || $DOCKER network create polari-link
echo -e "${G}[twin]${NC} polari-link network ready."

# ---- shared token (stable across re-runs) ---------------------------------
if [[ ! -f "$TOKEN_FILE" ]]; then
    head -c 24 /dev/urandom | base64 | tr -d '/+=' > "$TOKEN_FILE"
fi
TOKEN="$(cat "$TOKEN_FILE")"

# ---- 2. wire instance A ----------------------------------------------------
if $DOCKER ps --format '{{.Names}}' | grep -q '^prf-backend$'; then
    $DOCKER network connect polari-link prf-backend 2>/dev/null \
        && echo -e "${G}[twin]${NC} instance A joined polari-link." \
        || echo -e "${G}[twin]${NC} instance A already on polari-link."
    $DOCKER update --memory 1g --memory-swap 1g prf-backend >/dev/null
    echo -e "${G}[twin]${NC} instance A backend memory raised to 1 GB (dask sizing)."
    $DOCKER exec prf-backend sh -c "printf %s '$TOKEN' > /app/data/peer_token"
    echo -e "${G}[twin]${NC} peer token dropped into instance A."
else
    echo -e "${R}[error]${NC} prf-backend is not running — start instance A first (./rebuild-staging.sh)"; exit 1
fi

# ---- 3. B's frontend runtime config (plain-HTTP ports) --------------------
python3 - "$SCRIPT_DIR" "$LOCAL_IP" <<'EOF'
import json, sys
d, ip = sys.argv[1], sys.argv[2]
src = json.load(open(f'{d}/.generated/prf-runtime-config.json'))
cfg = dict(src)
cfg['_comment'] = 'TWIN INSTANCE B: generated by twin-polari-build.sh (plain HTTP ports)'
cfg['backend'] = {
    'http':  {'protocol': 'http', 'url': ip, 'port': '8081'},
    'https': {'protocol': 'http', 'url': ip, 'port': '8081'},
    'ws':    {'protocol': 'ws',   'url': ip, 'port': '8083'},
}
feats = dict(cfg.get('features') or {})
feats['enableHttps'] = False
cfg['features'] = feats
json.dump(cfg, open(f'{d}/.generated/prf-b-runtime-config.json', 'w'), indent=1)
print('runtime config for B written')
EOF

# ---- 4. instance B ----------------------------------------------------------
echo -e "${B}[twin]${NC} bringing up instance B…"
POLARI_PEER_TOKEN="$TOKEN" $DOCKER compose -p "$PROJECT_B" -f "$COMPOSE_B" up -d

echo -e "${B}[twin]${NC} waiting for instance B to be healthy (first boot seeds everything)…"
for i in $(seq 1 60); do
    state=$($DOCKER inspect -f '{{.State.Health.Status}}' prf-b-backend 2>/dev/null || echo starting)
    [[ "$state" == "healthy" ]] && break
    sleep 5
done
state=$($DOCKER inspect -f '{{.State.Health.Status}}' prf-b-backend 2>/dev/null || echo missing)
if [[ "$state" != "healthy" ]]; then
    echo -e "${R}[error]${NC} instance B not healthy after 5 min (state: $state) — check: $DOCKER logs prf-b-backend"; exit 1
fi
echo -e "${G}[twin]${NC} instance B healthy."

# ---- 5. peer registration handshake ----------------------------------------
# B learns about A (reachable as prf-backend over the shared networks):
curl -s -X POST "$B_API/api/peers/register" -H 'Content-Type: application/json' \
     -d "{\"name\": \"a\", \"baseUrl\": \"http://prf-backend:3000\", \"token\": \"$TOKEN\"}" >/dev/null \
    && echo -e "${G}[twin]${NC} registered A as a peer of B."
# A learns about B (reachable as prf-b-backend over polari-link):
curl -k -s -X POST "$A_API/api/peers/register" -H 'Content-Type: application/json' \
     -d "{\"name\": \"b\", \"baseUrl\": \"http://prf-b-backend:3000\", \"token\": \"$TOKEN\"}" >/dev/null \
    && echo -e "${G}[twin]${NC} registered B as a peer of A."

echo ""
echo -e "${G}[twin done]${NC} two Polari instances are linked."
echo "  - Instance A: https://prf.${LOCAL_IP}.nip.io   (api: $A_API)"
echo "  - Instance B: http://${LOCAL_IP}:8082          (api: $B_API)"
echo "  - Peers:      ./twin-polari-build.sh status"
echo "  - Stop B:     ./twin-polari-build.sh down"
